spring.application.name=amigo-invisible-backend
server.port=8080

# --- Base de datos Aiven (MySQL) ---
spring.datasource.url=jdbc:mysql://mysql-2910d7d6-fernandojs120-9e5f.l.aivencloud.com:15904/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_lp_E1rKhAIh__1f0LqL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- CORS: origen de tu app Angular en desarrollo ---
app.cors.allowed-origin=https://amigo-invisible-liard.vercel.app

# --- Token de sesion simple ---
app.auth.token-expiration-days=30